# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [3]:
url = r'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user'
users = pd.read_csv(url, sep='|')
users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

### Step 4. Discover what is the mean age per occupation

In [4]:
users.groupby('occupation').agg({'age':'mean'}).reset_index()

       occupation        age
0   administrator  38.746835
1          artist  31.392857
2          doctor  43.571429
3        educator  42.010526
4        engineer  36.388060
5   entertainment  29.222222
6       executive  38.718750
7      healthcare  41.562500
8       homemaker  32.571429
9          lawyer  36.750000
10      librarian  40.000000
11      marketing  37.615385
12           none  26.555556
13          other  34.523810
14     programmer  33.121212
15        retired  63.071429
16       salesman  35.666667
17      scientist  35.548387
18        student  22.081633
19     technician  33.148148
20         writer  36.311111

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [5]:
gb = users.groupby(['occupation','gender']).agg('count')['user_id'].reset_index()
gb.nunique()

occupation    21
gender         2
user_id       24
dtype: int64

In [6]:
gb[gb['gender'] == 'M']['user_id'].reset_index(drop=True)

0      43
1      15
2       7
3      69
4      65
5      16
6      29
7       5
8       1
9      10
10     22
11     16
12      5
13     69
14     60
15     13
16      9
17     28
18    136
19     26
20     26
Name: user_id, dtype: int64

In [7]:
count = gb[gb['gender'] == 'M']['user_id'].reset_index(drop=True) / gb[gb['gender'] == 'F']['user_id'].reset_index(drop=True).add(
    gb[gb['gender'] == 'M']['user_id'].reset_index(drop=True), fill_value=0)
count

0     0.544304
1     0.535714
2     0.212121
3     0.971831
4     0.970149
5     0.842105
6     0.725000
7     0.454545
8     0.333333
9     0.256410
10    0.687500
11    0.800000
12    0.121951
13    0.920000
14    0.983607
15    0.812500
16    0.750000
17    0.318182
18    0.992701
19    0.577778
20    1.000000
Name: user_id, dtype: float64

In [8]:
gbr = gb[gb['gender'] == 'M'].copy().reset_index()
gbr['ratio Male'] = count
gbr

    index     occupation gender  user_id  ratio Male
0       1  administrator      M       43    0.544304
1       3         artist      M       15    0.535714
2       4         doctor      M        7    0.212121
3       6       educator      M       69    0.971831
4       8       engineer      M       65    0.970149
5      10  entertainment      M       16    0.842105
6      12      executive      M       29    0.725000
7      14     healthcare      M        5    0.454545
8      16      homemaker      M        1    0.333333
9      18         lawyer      M       10    0.256410
10     20      librarian      M       22    0.687500
11     22      marketing      M       16    0.800000
12     24           none      M        5    0.121951
13     26          other      M       69    0.920000
14     28     programmer      M       60    0.983607
15     30        retired      M       13    0.812500
16     32       salesman      M        9    0.750000
17     34      scientist      M       28    0.318182
18     36        student      M      136    0.992701
19     38     technician      M       26    0.577778
20     40         writer      M       26    1.000000

In [9]:
users[(users['occupation'] == 'writer') & (users['gender'] =='M')]

     user_id  age gender occupation zip_code
2          3   23      M     writer    32067
20        21   26      M     writer    30068
21        22   25      M     writer    40206
27        28   32      M     writer    55369
49        50   21      M     writer    52245
195      196   49      M     writer    55105
198      199   30      M     writer    17604
200      201   27      M     writer    E2A4H
292      293   24      M     writer    60804
369      370   52      M     writer    08534
384      385   36      M     writer    10003
391      392   52      M     writer    59801
444      445   21      M     writer    92653
463      464   60      M     writer    94583
497      498   26      M     writer    55408
547      548   51      M     writer    95468
694      695   26      M     writer    38115
740      741   25      M     writer    63108
744      745   42      M     writer    55113
771      772   50      M     writer    27105
800      801   22      M     writer    92154
828      829   48      M     writer    80209
832      833   34      M     writer    90019
841      842   40      M     writer    93055
852      853   49      M     writer    40515
895      896   28      M     writer    91505

### Step 6. For each occupation, calculate the minimum and maximum ages

In [10]:
users.groupby('occupation').agg({'age':['min','max']}).reset_index()

       occupation age
                  min max
0   administrator  21  70
1          artist  19  48
2          doctor  28  64
3        educator  23  63
4        engineer  22  70
5   entertainment  15  50
6       executive  22  69
7      healthcare  22  62
8       homemaker  20  50
9          lawyer  21  53
10      librarian  23  69
11      marketing  24  55
12           none  11  55
13          other  13  64
14     programmer  20  63
15        retired  51  73
16       salesman  18  66
17      scientist  23  55
18        student   7  42
19     technician  21  55
20         writer  18  60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [11]:
users.groupby(['occupation','gender']).agg({'age':'mean'}).reset_index()

       occupation gender        age
0   administrator      F  40.638889
1   administrator      M  37.162791
2          artist      F  30.307692
3          artist      M  32.333333
4          doctor      M  43.571429
5        educator      F  39.115385
6        educator      M  43.101449
7        engineer      F  29.500000
8        engineer      M  36.600000
9   entertainment      F  31.000000
10  entertainment      M  29.000000
11      executive      F  44.000000
12      executive      M  38.172414
13     healthcare      F  39.818182
14     healthcare      M  45.400000
15      homemaker      F  34.166667
16      homemaker      M  23.000000
17         lawyer      F  39.500000
18         lawyer      M  36.200000
19      librarian      F  40.000000
20      librarian      M  40.000000
21      marketing      F  37.200000
22      marketing      M  37.875000
23           none      F  36.500000
24           none      M  18.600000
25          other      F  35.472222
26          other      M  34.028986
27     programmer      F  32.166667
28     programmer      M  33.216667
29        retired      F  70.000000
30        retired      M  62.538462
31       salesman      F  27.000000
32       salesman      M  38.555556
33      scientist      F  28.333333
34      scientist      M  36.321429
35        student      F  20.750000
36        student      M  22.669118
37     technician      F  38.000000
38     technician      M  32.961538
39         writer      F  37.631579
40         writer      M  35.346154

### Step 8.  For each occupation present the percentage of women and men

In [12]:
count_F = gb[gb['gender'] == 'F']['user_id'].reset_index(drop=True) / gb[gb['gender'] == 'F']['user_id'].reset_index(drop=True).add(
    gb[gb['gender'] == 'M']['user_id'].reset_index(drop=True), fill_value=0)
count.head()

0    0.544304
1    0.535714
2    0.212121
3    0.971831
4    0.970149
Name: user_id, dtype: float64

In [13]:
gbr['ratio Female'] = count_F
gbr

    index     occupation gender  user_id  ratio Male  ratio Female
0       1  administrator      M       43    0.544304      0.455696
1       3         artist      M       15    0.535714      0.464286
2       4         doctor      M        7    0.212121      0.787879
3       6       educator      M       69    0.971831      0.028169
4       8       engineer      M       65    0.970149      0.029851
5      10  entertainment      M       16    0.842105      0.157895
6      12      executive      M       29    0.725000      0.275000
7      14     healthcare      M        5    0.454545      0.545455
8      16      homemaker      M        1    0.333333      0.666667
9      18         lawyer      M       10    0.256410      0.743590
10     20      librarian      M       22    0.687500      0.312500
11     22      marketing      M       16    0.800000      0.200000
12     24           none      M        5    0.121951      0.878049
13     26          other      M       69    0.920000      0.080000
14     28     programmer      M       60    0.983607      0.016393
15     30        retired      M       13    0.812500      0.187500
16     32       salesman      M        9    0.750000      0.250000
17     34      scientist      M       28    0.318182      0.681818
18     36        student      M      136    0.992701      0.007299
19     38     technician      M       26    0.577778      0.422222
20     40         writer      M       26    1.000000           NaN

In [34]:
# Assuming your DataFrame is named df
# First, count the number of each gender for each occupation
counts = users.groupby(['occupation', 'gender']).size()
counts

occupation     gender
administrator  F          36
               M          43
artist         F          13
               M          15
doctor         M           7
educator       F          26
               M          69
engineer       F           2
               M          65
entertainment  F           2
               M          16
executive      F           3
               M          29
healthcare     F          11
               M           5
homemaker      F           6
               M           1
lawyer         F           2
               M          10
librarian      F          29
               M          22
marketing      F          10
               M          16
none           F           4
               M           5
other          F          36
               M          69
programmer     F           6
               M          60
retired        F           1
               M          13
salesman       F           3
               M           9
scientist      F           3
               M          28
student        F          60
               M         136
technician     F           1
               M          26
writer         F          19
               M          26
dtype: int64

In [33]:
# Then, calculate the total count for each occupation
total = users.groupby('occupation').size()
total

occupation
administrator     79
artist            28
doctor             7
educator          95
engineer          67
entertainment     18
executive         32
healthcare        16
homemaker          7
lawyer            12
librarian         51
marketing         26
none               9
other            105
programmer        66
retired           14
salesman          12
scientist         31
student          196
technician        27
writer            45
dtype: int64

In [39]:
# Calculate the ratio for each gender within each occupation
rationing = counts / total
rationing = rationing.reset_index(name='ratio')
rationing

       occupation gender     ratio
0   administrator      F  0.455696
1   administrator      M  0.544304
2          artist      F  0.464286
3          artist      M  0.535714
4          doctor      M  1.000000
5        educator      F  0.273684
6        educator      M  0.726316
7        engineer      F  0.029851
8        engineer      M  0.970149
9   entertainment      F  0.111111
10  entertainment      M  0.888889
11      executive      F  0.093750
12      executive      M  0.906250
13     healthcare      F  0.687500
14     healthcare      M  0.312500
15      homemaker      F  0.857143
16      homemaker      M  0.142857
17         lawyer      F  0.166667
18         lawyer      M  0.833333
19      librarian      F  0.568627
20      librarian      M  0.431373
21      marketing      F  0.384615
22      marketing      M  0.615385
23           none      F  0.444444
24           none      M  0.555556
25          other      F  0.342857
26          other      M  0.657143
27     programmer      F  0.090909
28     programmer      M  0.909091
29        retired      F  0.071429
30        retired      M  0.928571
31       salesman      F  0.250000
32       salesman      M  0.750000
33      scientist      F  0.096774
34      scientist      M  0.903226
35        student      F  0.306122
36        student      M  0.693878
37     technician      F  0.037037
38     technician      M  0.962963
39         writer      F  0.422222
40         writer      M  0.577778

In [43]:
usersRatio = pd.merge(users, rationing, on=['occupation', 'gender'], how='left')
usersRatio

     user_id  age gender     occupation zip_code     ratio
0          1   24      M     technician    85711  0.962963
1          2   53      F          other    94043  0.342857
2          3   23      M         writer    32067  0.577778
3          4   24      M     technician    43537  0.962963
4          5   33      F          other    15213  0.342857
..       ...  ...    ...            ...      ...       ...
938      939   26      F        student    33319  0.306122
939      940   32      M  administrator    02215  0.544304
940      941   20      M        student    97229  0.693878
941      942   48      F      librarian    78209  0.568627
942      943   22      M        student    77841  0.693878

[943 rows x 6 columns]