# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [4]:
url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv'
df = pd.read_csv(url)
df.T.iloc[:,:6]

                  0        1        2         3       4           5
school           GP       GP       GP        GP      GP          GP
sex               F        F        F         F       F           M
age              18       17       15        15      16          16
address           U        U        U         U       U           U
famsize         GT3      GT3      LE3       GT3     GT3         LE3
Pstatus           A        T        T         T       T           T
Medu              4        1        1         4       3           4
Fedu              4        1        1         2       3           3
Mjob        at_home  at_home  at_home    health   other    services
Fjob        teacher    other    other  services   other       other
reason       course   course    other      home    home  reputation
guardian     mother   father   mother    mother  father      mother
traveltime        2        1        1         1       1           1
studytime         2        2        2         3       2           2
failures          0        0        3         0       0           0
schoolsup       yes       no      yes        no      no          no
famsup           no      yes       no       yes     yes         yes
paid             no       no      yes       yes     yes         yes
activities       no       no       no       yes      no         yes
nursery         yes       no      yes       yes     yes         yes
higher          yes      yes      yes       yes     yes         yes
internet         no      yes      yes       yes      no         yes
romantic         no       no       no       yes      no          no
famrel            4        5        4         3       4           5
freetime          3        3        3         2       3           4
goout             4        3        2         2       2           2
Dalc              1        1        2         1       1           1
Walc              1        1        3         1       2           2
health            3        3        3         5       5           5
absences          6        4       10         2       4          10
G1                5        5        7        15       6          15
G2                6        5        8        14      10          15
G3                6        6       10        15      10          15

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [5]:
df.loc[:,'school':'guardian'].head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father

### Step 5. Create a lambda function that will capitalize strings.

In [7]:
lamd = lambda x:x.capitalize()

### Step 6. Capitalize both Mjob and Fjob

In [12]:
df['Mjob'] = df['Mjob'].apply(lamd)

In [13]:
df['Fjob'] = df['Fjob'].apply(lamd)

### Step 7. Print the last elements of the data set.

In [14]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
390,MS,M,20,U,LE3,A,2,2,Services,Services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,Services,Services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,Other,Other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,Services,Other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,Other,At_home,...,3,2,3,3,3,5,5,8,9,9

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

0

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [20]:
majority = lambda x:True if x >= 17 else False
df['legal_drinker'] = df['age'].apply(majority)

In [25]:
majority = lambda x: True if x >= 17 else False
df['legal_drinker'] = df['age'].apply(majority)
df.T.iloc[:,-5:-1]

                    390       391     392       393
school               MS        MS      MS        MS
sex                   M         M       M         M
age                  20        17      21        18
address               U         U       R         R
famsize             LE3       LE3     GT3       LE3
Pstatus               A         T       T         T
Medu                  2         3       1         3
Fedu                  2         1       1         2
Mjob           Services  Services   Other  Services
Fjob           Services  Services   Other     Other
reason           course    course  course    course
guardian          other    mother   other    mother
traveltime            1         2       1         3
studytime             2         1       1         1
failures              2         0       3         0
schoolsup            no        no      no        no
famsup              yes        no      no        no
paid                yes        no      no        no
activities           no        no      no        no
nursery             yes        no      no        no
higher              yes       yes     yes       yes
internet             no       yes      no       yes
romantic             no        no      no        no
famrel                5         2       5         4
freetime              5         4       5         4
goout                 4         5       3         1
Dalc                  4         3       3         3
Walc                  5         4       3         4
health                4         2       3         5
absences             11         3       3         0
G1                    9        14      10        11
G2                    9        16       8        12
G3                    9        16       7        10
legal_drinker      True      True    True      True

### Step 10. Multiply every number of the dataset by 10.
##### I know this makes no sense, don't forget it is just an exercise

In [29]:
df.apply(lambda x: x*10 if x.dtype.kind in 'iufc' else x)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,...,30,40,10,10,30,60,50,60,60,True
1,GP,F,170,U,GT3,T,10,10,At_home,Other,...,30,30,10,10,30,40,50,50,60,True
2,GP,F,150,U,LE3,T,10,10,At_home,Other,...,30,20,20,30,30,100,70,80,100,False
3,GP,F,150,U,GT3,T,40,20,Health,Services,...,20,20,10,10,50,20,150,140,150,False
4,GP,F,160,U,GT3,T,30,30,Other,Other,...,30,20,10,20,50,40,60,100,100,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,200,U,LE3,A,20,20,Services,Services,...,50,40,40,50,40,110,90,90,90,True
391,MS,M,170,U,LE3,T,30,10,Services,Services,...,40,50,30,40,20,30,140,160,160,True
392,MS,M,210,R,GT3,T,10,10,Other,Other,...,50,30,30,30,30,30,100,80,70,True
393,MS,M,180,R,LE3,T,30,20,Services,Other,...,40,10,30,40,50,0,110,120,100,True
394,MS,M,190,U,LE3,T,10,10,Other,At_home,...,20,30,30,30,50,50,80,90,90,True